sudo: required

services:
  - docker

before_instal:
  - docker build -t banuaraidi/api-todo -f ./backend/Dockerfile ./backend

script:
  - docker run banuaraidi/api-todo npm test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push banuaraidi/api-todo

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: react-demo
  env: ReactDemo-env
  bucket_name: elasticbeanstalk-ap-southeast-1-040596896543
  bucket_path: react-demo
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY