version: "3.7"
services:
  # backend service
  backend:
    # image: react-demo_backend
    build: 
      context: ./backend/
      dockerfile: Dockerfile
      # args: 
        # HOST_DB: ${postgres}
    expose:
      - ${DOCKER_API_PORT}
    ports:
      - ${APP_API_PORT}:${DOCKER_API_PORT}
    environment: 
      SERVERPORT: ${DOCKER_API_PORT}
      DB_HOST: postgres
      DB_USER: test
      DB_PASSWORD: secret
      DB_NAME: demo
      WAIT_HOSTS: postgres:5432
      WAIT_HOSTS_TIMEOUT: 90
    depends_on: 
      - postgres

  # postgre service
  postgres:
    image: postgres:12-alpine
    environment: 
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "demo"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # frontend service
  frontend:
    # image: react-demo_frontend
    build: ./frontend
    expose: 
      - ${DOCKER_CLIENT_PORT}
    ports: 
      - ${APP_CLIENT_PORT}:${DOCKER_CLIENT_PORT}
    links:
      - backend
    depends_on: 
      - backend

volumes: 
  pg_data: