version: "3.7"
services:
  # backend service
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
      # args: 
        # HOST_DB: ${postgres}
    ports:
      - "3001:3001"
    environment: 
      DB_HOST: postgres
      DB_USER: test
      DB_PASSWORD: secret
      DB_NAME: demo
      WAIT_HOSTS: postgres:5432
      WAIT_HOSTS_TIMEOUT: 90
    depends_on: 
      - postgres

  # postgre service
  postgres:
    image: postgres:12-alpine
    environment: 
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "demo"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # frontend service
  frontend:
    build: ./frontend
    ports: 
      #  - "3000:3002"
      - "80:80"
    depends_on: 
      - backend

volumes: 
  pg_data: